### ISSUE TITLE
Port remaining fitness functions to Atomese

### ISSUE THREAD

**Issue by Bitseat** [singnet/as-moses#15]
All the functions inheriting bscore_base other than logical_bscore  are
```discritize_contin_bscore
cluster_bscore
enum_table_bscore
interesting_predicate_bscore
ss_bscore
contin_bscore
precision_conj_bscore
bscore_ctable_base
bscore_ctable_time_dispersion
ctruth_table_bscore 
discriminating_bscore
select_bscore
```

All these 12 functions need to be ported to atomese. The porting will have 3 iterations. we start from the simple. of course, 'simple' depends on our understanding so correct me if i'm wrong.
The functions to be ported in the first iteration are
```
        *contin_bscore
	*discritize_contin_bscore
	*cluster_bscore- considered experimental, doesn't yet work very well for combo. redesign or remove
```

what the above functions need is an OTable and ITable

In the second iteration
First, bscore_ctable_base will be ported. It is the base class for fitness functions that use a ctable. Provides useful table compression. The functions below inherits from it
```
        *ctruth_table_bscore - compute behavioral score for boolean truth tables.
	*bscore_ctable_time_dispersion
	*discriminating_bscore - Base class for precision, recall, senstivity, specificty, F-score, etc. type discriminator scorers.
	*select_bscore - Fitness function for selecting a range of rows from a continuous-valued distribution.
```

At last,
```
        *enum_table_bscore - Like ctruth_table_bscore, but for enums. That is, the output column of the table is assumed to be enum-valued.
	*precision_conj_bscore - A bit like precision but tries to maximize the number conjunctions after precision. It blatantly assumes that the domain is boolean.
	*interesting_predicate_bscore - Bscore to find interesting predicates.
```

all the above functions rely on CTable. 

I believe ss_bscore can be done first or at last.

@ngeiswei , your suggestion on CTable implementation detail and functions that need to be added or removed is very important.

**Comment by ngeiswei** [comment]
@Bitseat, for now you only need to focus on fitness functions that covered by unit tests, for the rest we'll see on a case-by-case basis.

I'll come back to you on CTable soon.

**Comment by ngeiswei** [comment]
@Bitseat regarding supporting CTable, I don't see a better option than creating a new value type (inherited from `ProtoAtom`) to store a column of distributions as opposed to single values. So basically, the steps would be

1. Create such distribution sequence value.
2. Upgrading the atomese interpreter to support this new type.

Before proceeding I think the ProtoAtom code needs some improvements, I'll take care of that, after which I'll post a detailed issue about it and you or someone else can take care of it.

Meanwhile you may obviously start porting fitness functions that do not use CTable. In anyway case it's to not try to do too many things at once, certain for the first few steps, so you should probably focus one single fitness, make it work, create a PR, and then move on to more fitnesses.

**Comment by Bitseat** [comment]
ok @ngeiswei , we'll do that. Thank you.
