### ISSUE TITLE
A file in two directories

### ISSUE THREAD

**Issue by yitbrek** [singnet/as-moses#28]
The file precision.csv is found on two directories 
as-moses/tests/moses/scoring/
and
as-moses/tests/moses/main/

**Comment by ngeiswei** [comment]
Thanks for your report, @yitbrek. However `precision.csv` is used in both tests in `scoring` and `main` directories so I feel it's OK to be duplicated in that instance.

**Comment by yitbrek** [comment]
@ngeiswei  scorng/precision.csv is not used.

**Comment by kasimebrahim** [comment]
@yitbrek scoringUTest is supposed to use 'test/moses/scoring/precision.csv',
<pre>
const string mosesUTest_dir=string(PROJECT_SOURCE_DIR) + "/tests/moses/main/";
</pre>
should be corrected as 
<pre>
const string mosesUTest_dir=string(PROJECT_SOURCE_DIR) + "/tests/moses/scoring/";
</pre>

**Comment by ngeiswei** [comment]
Oh true, I suppose `mosesUTest_dir should also be renamed `scoringUTest_dir`.

**Comment by ngeiswei** [comment]
Fixed in #30
