### ISSUE TITLE
Change install path to `PREFIX/include/opencog` and `PREFIX/lib/opencog`

### ISSUE THREAD

**Issue by ngeiswei** [singnet/as-moses#37]
As AS-MOSES is gonna get more and more integrated to opencog it makes sense to change its installation paths to `PREFIX/include/opencog` (i.e. `/usr/local/include/opencog`) for headers and `PREFIX/lib/opencog` (i.e. `/usr/local/include/opencog`) for libraries.

**Comment by kasimebrahim** [comment]
I do agree.And how about changing  `as-moses/moses` to `as-moses/opencog`.

**Comment by ngeiswei** [comment]
Yes, absolutely!

**Comment by Bitseat** [comment]
@ngeiswei & @kasimebrahim , see the changes made here https://github.com/Bitseat/as-moses/tree/asmoses_IP_change

**Comment by ngeiswei** [comment]
@Bitseat it seems you have copied rather than moved. You need to do the moving (adding and deleting) of files with the same commit, that way git will recognize that it's a move and it will be a lot easier to review.

**Comment by Bitseat** [comment]
oh I see what you mean @ngeiswei . yeah that's a big mistake. I'll make the correction.

**Comment by Bitseat** [comment]
@ngeiswei corrected here. https://github.com/Bitseat/as-moses/tree/asmoses-to-opencog

**Comment by ngeiswei** [comment]
@Bitseat, there's compile error for python bindings, you need to install cython on your machine in order to test it.

**Comment by Bitseat** [comment]
@ngeiswei , sorry for pushing it without running the tests. I do have cython on my machine but 'CythonMoses' did fail as a result of path issue. This time it compiled successfully and all the tests has passed. can you please check it  again. https://github.com/Bitseat/as-moses/tree/asmoses-to-opencog

**Comment by ngeiswei** [comment]
Great, I didn't check but I think you can create a PR at that point and we can keep the interaction on that PR.
