### ISSUE TITLE
Incoming set is not working.

### ISSUE THREAD

**Issue by yitbrek** [singnet/as-moses#39]
Outgoing set works fine but  Incoming set is not.

When executed it returns:

/usr/include/boost/variant/variant.hpp: In instantiation of ‘typename boost::enable_if<boost::is_rvalue_reference<T&&> >::type boost::variant<T0, TN>::convert_construct(T&&, int, mpl_::false_) [with T = std::vector<std::shared_ptr<opencog::Link> >; T0_ = double; TN = {opencog::combo::enum_t, opencog::combo::id::builtin, opencog::combo::id::wild_card, opencog::combo::argument, opencog::combo::id::action, const opencog::combo::builtin_action_base*, const opencog::combo::perception_base*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, const opencog::combo::indefinite_object_base*, opencog::combo::message, const opencog::combo::procedure_call_base*, const opencog::combo::action_symbol_base*, opencog::combo::ann_type}; typename boost::enable_if<boost::is_rvalue_reference<T&&> >::type = void; mpl_::false_ = mpl_::bool_<false>]’:
/usr/include/boost/variant/variant.hpp:1732:26:   required from ‘boost::variant<T0, TN>::variant(T&&, typename boost::enable_if<boost::is_rvalue_reference<T&&> >::type*, typename boost::disable_if<boost::is_const<C> >::type*) [with T = std::vector<std::shared_ptr<opencog::Link> >; T0_ = double; TN = {opencog::combo::enum_t, opencog::combo::id::builtin, opencog::combo::id::wild_card, opencog::combo::argument, opencog::combo::id::action, const opencog::combo::builtin_action_base*, const opencog::combo::perception_base*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, const opencog::combo::indefinite_object_base*, opencog::combo::message, const opencog::combo::procedure_call_base*, const opencog::combo::action_symbol_base*, opencog::combo::ann_type}; typename boost::enable_if<boost::is_rvalue_reference<T&&> >::type = void; typename boost::disable_if<boost::is_const<C> >::type = void]’

**Comment by ngeiswei** [comment]
@yitbrek could you paste the steps to reproduce the problem? Otherwise it's difficult to help.

**Comment by yitbrek** [comment]
AtomSpace as;
Handle h = as.add_node(NUMBER_NODE, "2");
Handle y=as.add_node(NUMBER_NODE,"3");
Handle l=as.add_link(PLUS_LINK,h,y);
// for out going set
cout<<l->getOutgoingSet();
// for incoming set
cout<<h->getIncomingSet();

**Comment by yitbrek** [comment]
AtomSpace as;
Handle h = as.add_node(NUMBER_NODE, "2");
Handle y=as.add_node(NUMBER_NODE,"3");
Handle l=as.add_link(PLUS_LINK,h,y);
// for out going set
cout<< l->getOutgoingSet();
// for incoming set
cout<< h->getIncomingSet();

**Comment by ngeiswei** [comment]
@yitbrek I don't see anything wrong with that code as it stands, the problem likely comes from the interaction with as-moses.

What you should do is put that exact buggy code in a branch of as-moses on your user account, and let me know the name of that branch, which I can then locally clone and test.

**Comment by ngeiswei** [comment]
I have no problem this it, @yitbrek , are you sure you compiled and installed the `singnet` masters of `cogutil` and `atomspace`?

Note that current `opencog/cogutil` and `opencog/atomspace` are incompatible, this should be sorted soon though (hopefully this week).

**Comment by ngeiswei** [comment]
Actually I can reproduce it (now that I'm compiling the unit tests), let me look into it...

**Comment by ngeiswei** [comment]
@yitbrek, you're right, `std::operator<<` has not be overloaded for `IncomingSet`. It seems you have 2 options:

1. Use `oc_to_string` that is overloaded for `IncomingSet`
2. Overload `std::operator<<` for `IncomingSet` (which would probably call `oc_to_string`)

The reason I introduced `oc_to_string` was to support an indentation argument while being able to be called by gdb, but supporting `operator<<` is obviously a good thing too. So feel free to go with option 2 if you want (just do that on `opencog/atomspace`, not `singnet/atomspace` as it is touching the core).

**Comment by yitbrek** [comment]
@ngeiswei ok I will do that.
